version: '3.7'

services:
  vault:
    image: vault:1.5.0
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./logs:/vault/logs
      - ./file:/vault/file
      - ./config:/vault/config
      - ./policies:/vault/policies
    entrypoint: vault server -config=/vault/config/file-storage.hcl
    networks:
      - cloud-security

networks:
  cloud-security: